version: '3.4'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./etc/db:/db
      - ./data/mysql:/var/lib/mysql
      - ./etc/mysql.ini:/etc/mysql/conf.d/my.ini # config file
      - ./etc/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 3306

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6379

  php:
    build: etc/php
    volumes:
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    ports:
      - 9000

  mail:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - mariadb
      - php
      - redis
      - mail
    depends_on:
      - php
      - mariadb
      - redis
      - mail