version: '3.3'

services:

  mariadb:
    image: mariadb:latest
    environment:
      TZ: Europe/Prague
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    restart: always
    volumes:
      - ./etc/db:/db
      - ./data/mysql:/var/lib/mysql
      - ./etc/mysql.ini:/etc/mysql/conf.d/my.ini # config file
      - ./etc/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 3306

  php:
    build: etc/php
    depends_on:
      - mariadb
    volumes:
      - ./etc/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    ports:
      - 9000

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - mariadb
      - php
    links:
      - mariadb
      - php